version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=sua_chave_secreta_aqui
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - STATIC_URL=/static/
      - STATIC_ROOT=/app/staticfiles

volumes:
  static_volume: